### ISSUE TITLE
Hello, I would like to ask whether this software has been evaluated for LOD?

### ISSUE THREAD

**Issue by jsonProgram** [JustinChu/ntsm#2]
1. Mainly wondering if NTSM is suitable for low coverage NGSdata?
2. In other words, how much depth of NGSdata can it be applied to?

**Comment by JustinChu** [comment]
Sorry for the late reply. ntsm has been tested on 1x coverage (Illumina) and is generally pretty successful. Due to missing sites however, it will not use the PCA-based heuristic but this should be a problem unless you have thousands of samples.

This depends on the quality of the data, low coverage Nanopore data will need higher coverage for example.
