### ISSUE TITLE
Failed to generate sites.fa file for other mammals

### ISSUE THREAD

**Issue by yangqimeng99** [JustinChu/ntsm#8]
Dear Author:

I am using the ntsm tool (v1.0.1) to verify the correct correspondence of multiple sequencing samples from the same individual. However, I encountered challenges when applying it to non-human mammals, specifically in generating the `sites.fa` file for my species of study.

**Attempted Process:**
I filtered out nearly 900,000 biallelic SNPs with `0.45 <= MAF <= 0.55` from a collection of several thousand samples and used the reference genome file as an input for the following command:
```
generateSites name=sites ref=genome.fa vcf=panel-MAF0.45-0.55.vcf t=10
```
The command successfully generated the `sites.sam` file. However, when running `perl scripts/filterRepetiveSNP.pl`, all records in the `sites.sam` file were reported as **“unable to parse:”**, resulting in an empty `sites.fa` file. I am quite puzzled by this issue.

**Questions:**
Parsing Failure: Why do all records in the sites.sam file fail to parse in the filterRepetiveSNP.pl script?
Generalizability: According to your paper, after generating a carefully screened sites.fa file for a species, it should theoretically be usable within the species without considering differences between different populations. Does my current SNP site screening process meet this generalizability requirement?

Thank you for any guidance and assistance you can provide!

**Comment by JustinChu** [comment]
Hi,
It might be a bug. Can you send a sample of the VCF file used?
Thanks

**Comment by JustinChu** [comment]
Oh, it may be an already known/resolved bug https://github.com/JustinChu/ntsm/issues/4 . Can you pull the repo and run it from source?

I will probably do another full release soon with this fix as I plan on adding the tool to conda anyway.

**Comment by yangqimeng99** [comment]
Hi,
I have successfully pulled the debug version as per your suggestion and am currently in the process of testing it. I will provide feedback shortly.

Your help has been invaluable, and I greatly appreciate your timely response and efforts.

**Comment by yangqimeng99** [comment]
I hope this message finds you well. 

Following your recommendation, I used the new `filterRepetiveSNP.pl`, and the generateSites process successfully completed, yielding a sites.fa file.

However, the resulting `sites.fa` file only contains 802 sequences, which amounts to 401 pairs of variant sites. Given that the input VCF file contained 913,313 biallelic SNP sites In the log file generated during the `generateSites` run, there are 119,953 warnings similar to: `Warning: 1_516064_T_A A T is not a purine <-> pyrimidine variant.` This indicates that the majority of SNP sites were not retained in the `sites.fa` file, and it is quite perplexing as to why they were filtered out.

Despite the unexpected output from `generateSites`, I proceeded with the `ntsmCount` command using the generated `sites.fa` file:

```
ntsmCount -t 4 -m 10 -s ../sites.fa ${fastq_path}/${sample}_1.fastq.gz ${fastq_path}/${sample}_2.fastq.gz > ${sample}.counts.txt
```

For all the samples processed, the command consistently output around 250 records before encountering the following similar error:
```
terminate called after throwing an instance of 'std::out_of_range'
  what():  Couldn't find key.
ntsmCount.sh: line 3: 3757706 Aborted                 (core dumped) ntsmCount -t 4 -m 10 -s ../sites.fa ${fastq_path}/${sample}_1.fastq.gz ${fastq_path}/${sample}_2.fastq.gz > ${sample}.counts.txt
```

I would greatly appreciate your attention to these two issues and any insights you can provide. Your assistance is invaluable, and I look forward to resolving these problems.

Thank you very much for your continued support.

**Comment by JustinChu** [comment]
The warning not should be a major issue and is in place as a way of using more reliable sites. The reasoning is that it is common via human scripting/curation errors to accidentally swap the variants or orientation between A<->T or C<->G variants (i.e. A/T<->C/G is more reliable). However, it is just a warning and can be suppressed in the script with `--ignoreReq`.

However, if you have such a small number of sites in the file, something else seems to be going wrong. If possible, the easiest way to debug would be for you to send me parts of the VCF file and perhaps even the genome that you are using.

**Comment by JustinChu** [comment]
> Generalizability: According to your paper, after generating a carefully screened sites.fa file for a species, it should theoretically be usable within the species without considering differences between different populations. Does my current SNP site screening process meet this generalizability requirement?

I just realized I never answered this question. I think your screening just based on MAF should be good enough. Differences in population should be fine even if the sites don't exist in some of the samples in your population because the code can handle missing sites.

I think the `std::out_of_range` error you are seeing is due to something in the sites.fa file. Maybe some kind of truncation bug or something. Again I think I can help if you can point me to part of the input vcf and reference genome.

**Comment by yangqimeng99** [comment]
Thank you very much for your continued support and dedication to this project!

I’ve uploaded both the VCF and genome FASTA files I’m using to [Google Drive](https://drive.google.com/drive/folders/1jov6pTQOFEGHPI3axgq6VvvDPzuIZY_8?usp=sharing). If you could help me investigate the reason for a large number of SNP sites being lost during the generation of sites.fa, I would be extremely grateful.

**Comment by JustinChu** [comment]
I was unable to exactly reproduce your issues but it did bring my attention to the fact that I don't check for k-mers that are shared between sites because of their proximity to each other along with some other changes like more easily determining what value of `n` to use.

Regarding shared k-mers, in the sites vcf files I generated, I removed all SNPs within a certain distance of each other, which is one of the reasons I didn't run into these issues before. I've modified the pipeline/scripts to compensate for this allowing it to work on your input VCF file. It now removes shared k-mers, rather than remove sites in close proximity but I think this method will be more robust for a variety of inputs.

Attached is a sites fasta file that I think should work well for your purposes (87296 sites). It would help me on your end to test if you can also get the same output file with the current master branch. Thanks.
[Bos_taurus_ntsm_sites_n9.fa.gz](https://github.com/user-attachments/files/17770118/Bos_taurus_ntsm_sites_n9.fa.gz)

**Comment by yangqimeng99** [comment]
Good news! I used the current main branch (a64425a9064dd9a1a214b92cd3df12bb4feb8f93) and followed the previous command to complete the entire analysis workflow. 

During the generateSites process, I generated the `sites_n9.fa` file, which is exactly the same as the `Bos_taurus_ntsm_sites_n9.fa` file you provided. The only point of confusion is that I generated 13 sites files: `sites_n{0..12}.fa`. I'm not sure why this happened, and if possible, could you please explain why and let me know which one should be used for subsequent analysis?

Afterwards, I completed the entire analysis based on sites_n9.fa. The whole process ran without any errors, and I obtained perfect results. In the final summary.tsv file, the samples identified as being from the same individual matched my expectations exactly, which demonstrates the powerful reliability of this tool. I believe that **ntsm** will play a significant role now that multiple sequencing technologies are used in parallel!

Since the current main branch hasn't been released as an official version yet, could you please let me know when it will be officially released? I would like to switch to the official version of **ntsm** for long-term use.

Thank you very much for your support!

**Comment by JustinChu** [comment]
Yeah I'm going to clean up a few things and will try to make the next release ready to be put on conda. 

The multitude of files fasta `n` files was an attempt to streamline the process. Basically it takes as much computation to make all files rather than a specific `n` I figured why not make all of them allowing the user to pick the best one based on their needs.

**Comment by JustinChu** [comment]
New official version here: https://github.com/JustinChu/ntsm/releases/tag/1.1.0
